language: node_js
sudo: false
node_js:
  - lts/*
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
- cd client && npm run test-setup
- npm run test-server
script:
- npm run test-standard
- npm run test-node